#!/usr/bin/env python3
"""Vendor shared libs into an app folder and stamp build constants.

The badge has no cross-app dependency mechanism — every app must be
self-contained — so libs/spmono is copied into apps/<app>/spmono before any
deploy. The copy and _build.py are generated (gitignored).

Usage: python tools/vendor.py <app> [--release]
"""

import argparse
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def read_version(app_dir):
    toml = app_dir / "tildagon.toml"
    if toml.exists():
        for line in toml.read_text().splitlines():
            line = line.strip()
            if line.startswith("version"):
                return line.split("=", 1)[1].strip().strip('"')
    return "0.00.00"


def vendor(app, release=False):
    app_dir = ROOT / "apps" / app
    if not app_dir.is_dir():
        sys.exit(f"no such app: {app_dir}")
    src = ROOT / "libs" / "spmono"
    dst = app_dir / "spmono"
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst, ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
    build = app_dir / "_build.py"
    build.write_text(
        "# Generated by tools/vendor.py - do not edit.\n"
        f'VERSION = "{read_version(app_dir)}"\n'
        f"DEBUG = {not release}\n"
    )
    print(f"vendored spmono -> {dst}  (release={release})")
    return app_dir


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("app")
    parser.add_argument("--release", action="store_true")
    args = parser.parse_args()
    vendor(args.app, args.release)
